services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "spacex"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d spacex"]
      interval: 1s
      timeout: 5s
      retries: 10
  spacex:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
